Backend\UchetBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: Backend\UchetBundle\Repository\CategoriesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
