<?php

namespace Backend\UchetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostsRepository extends EntityRepository
{
}
